name: Android Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Gluon Build Action
        uses: gluonhq/gluon-build-action@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          gluon-target: android
          project-type: maven

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: StudentManagementSystem-Android
          path: target/gluonfx/aarch64-android/gvm/*.apk
